language: scala
sudo: false

scala:
  - 2.11.8

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_script:
  - travis_retry sbt ++$TRAVIS_SCALA_VERSION cassovary-core/update

script:
  - sbt ++$TRAVIS_SCALA_VERSION cassovary-core/test
